spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost/mybank_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true

server:
  port: 8082
  servlet:
    context-path: /api
    
jwt:
  secret: minha secret
